# Generated by Django 4.2.4 on 2023-08-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipts",
            name="ingridients",
            field=models.ManyToManyField(
                related_name="ingridients",
                to="api.ingridients",
                verbose_name="Ингридиенты",
            ),
        ),
        migrations.AlterField(
            model_name="receipts",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tags",
                to="api.tags",
                verbose_name="Тег",
            ),
        ),
    ]
