# Generated by Django 4.2.4 on 2023-08-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recipes_alter_ingridients_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridients',
            name='measurement_unit',
            field=models.CharField(verbose_name='Единица измерения'),
        ),
    ]
