# Generated by Django 4.2.4 on 2023-09-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_ingredientrecipe_favorite_buylist_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipes",
            old_name="cook_time",
            new_name="cooking_time",
        ),
        migrations.RenameField(
            model_name="recipes",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="recipes",
            old_name="text_description",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="tags",
            old_name="hex_code",
            new_name="color",
        ),
        migrations.RenameField(
            model_name="tags",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="recipes",
            name="ingridients",
        ),
        migrations.RemoveField(
            model_name="recipes",
            name="tag",
        ),
        migrations.AddField(
            model_name="recipes",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes", to="api.ingridients", verbose_name="Ингридиенты"
            ),
        ),
        migrations.AddField(
            model_name="recipes",
            name="is_favorited",
            field=models.BooleanField(default=False, verbose_name="В избранном ли"),
        ),
        migrations.AddField(
            model_name="recipes",
            name="is_in_shopping_cart",
            field=models.BooleanField(
                default=False, verbose_name="Находится ли в корзине"
            ),
        ),
        migrations.AddField(
            model_name="recipes",
            name="tags",
            field=models.ManyToManyField(
                related_name="recipes", to="api.tags", verbose_name="Тег"
            ),
        ),
    ]
